# borrowed in part from: https://medium.com/@HoussemDellai/run-selenium-ui-tests-in-docker-containers-f41ae2796b8d
services:
    hub:
        image: selenium/hub:latest
        container_name: hub
        ports:
            - "4444:4444"
        expose:
            - 4444
    chrome:
        image: selenium/node-chrome:latest
        deploy:
            replicas: 3
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
            - HUB_PORT=4444
    firefox:
        image: selenium/node-firefox:latest
        deploy:
            replicas: 3
        volumes: 
            - /dev/shm:/dev/shm
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
            - HUB_PORT=4444
    tests:
        image: selenium-tests
        container_name: tests
        depends_on:
            - hub
            - chrome
            - firefox
        environment:
            - HUB_PORT=4444
        volumes:
            - type: bind
              source: ./src
              target: /src